service: portfolio-api-serverless

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1
  
resources:
  - ${file(resources/api-gateway-errors.yml)}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
      - http:
          method: any
          path: /{any+}
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false